### PR TITLE
allow pedanticism

### PR DESCRIPTION
**Pull request by robertleeplummerjr**
When one needs to use operative for something resource intensive, such as streaming json (see http://developerblog.redhat.com/2014/05/20/communicating-large-objects-with-web-workers-in-javascript/ ) it may be ideal to have more than one callback, but in doing so may be somewhat pedantic for the every day implementation.

### CODE REVIEW

**Comment by robertleeplummerjr** [comment]
I have this now working flawlessly with loading large json into web workers, and then streaming it to the ui thread.  I might add that currently I'm streaming over 200mb, from multiple files, with no freezing on the ui thread.  As a reference, I used this article: http://developerblog.redhat.com/2014/05/20/communicating-large-objects-with-web-workers-in-javascript/ with operative, and created this: https://github.com/Spreadsheets/jQuery.sheet/blob/master/Sheet/thread.js

The result loads to the end user in under a second.  Truly outstanding.

**Comment by padolsey** [comment]
Sorry for not responding sooner. Persisting callbacks has been brought up before (see #15) and has made it into [0.4.0rc1](https://github.com/padolsey/operative/tree/0-4-rc1). I'm currently working on a clean-up which'll result in 0.4.0 hopefully being officially released (after rc1 and rc2) and much more clarity about the current state of the master branch. Sorry it's pretty unclear atm... been quite busy lately.

**Comment by robertleeplummerjr** [comment]
ok.  But my solution is pretty easy and straightforward... and it is
already committed.

On Wed, Apr 8, 2015 at 4:59 PM, James Padolsey <notifications@github.com>
wrote:

> Sorry for not responding sooner. Persisting callbacks has been brought up
> before (see #15 <https://github.com/padolsey/operative/issues/15>) and
> has made it into 0.4.0rc1
> <https://github.com/padolsey/operative/tree/0-4-rc1>. I'm currently
> working on a clean-up which'll result in 0.4.0 hopefully being officially
> released (after rc1 and rc2) and much more clarity about the current state
> of the master branch. Sorry it's pretty unclear atm... been quite busy
> lately.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/padolsey/operative/pull/30#issuecomment-91035923>.
>



-- 
Robert Plummer

**Comment by robertleeplummerjr** [comment]
Sorry, I missread.  I didn't think you had already committed.

On Wed, Apr 8, 2015 at 5:43 PM, Robert Plummer <robertleeplummerjr@gmail.com
> wrote:

> ok.  But my solution is pretty easy and straightforward... and it is
> already committed.
>
> On Wed, Apr 8, 2015 at 4:59 PM, James Padolsey <notifications@github.com>
> wrote:
>
>> Sorry for not responding sooner. Persisting callbacks has been brought up
>> before (see #15 <https://github.com/padolsey/operative/issues/15>) and
>> has made it into 0.4.0rc1
>> <https://github.com/padolsey/operative/tree/0-4-rc1>. I'm currently
>> working on a clean-up which'll result in 0.4.0 hopefully being officially
>> released (after rc1 and rc2) and much more clarity about the current state
>> of the master branch. Sorry it's pretty unclear atm... been quite busy
>> lately.
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/padolsey/operative/pull/30#issuecomment-91035923>.
>>
>
>
>
> --
> Robert Plummer
>



-- 
Robert Plummer

**Comment by padolsey** [comment]
0.4.0 is now released :)

See http://jsfiddle.net/phnt4pf2/1/

**Comment by robertleeplummerjr** [comment]
you rock.


On Fri, Apr 10, 2015 at 1:21 PM, James Padolsey <notifications@github.com>
wrote:

> Closed #30 <https://github.com/padolsey/operative/pull/30>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/padolsey/operative/pull/30#event-278316974>.
>



-- 
Robert Plummer

**Pull request closed without merging**
